// ⚠️  Auto-generated by 'npm run deploy' — do not edit manually
//    'npm run deploy'         → localhost 배포
//    'npm run deploy:sepolia' → Sepolia 배포
export const deployedContracts = {
  "sepolia": {
    "TipJar": {
      "address": "0x2261510c079468BA3F6c21ea29948d8Ee4a14c67",
      "abi": [
        {
          "inputs": [],
          "stateMutability": "nonpayable",
          "type": "constructor"
        },
        {
          "anonymous": false,
          "inputs": [
            { "indexed": true, "internalType": "address", "name": "owner", "type": "address" },
            { "indexed": false, "internalType": "uint256", "name": "amount", "type": "uint256" }
          ],
          "name": "TipWithDrawn",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            { "indexed": true, "internalType": "address", "name": "tipper", "type": "address" },
            { "indexed": false, "internalType": "uint256", "name": "amount", "type": "uint256" }
          ],
          "name": "Tiprecv",
          "type": "event"
        },
        {
          "inputs": [],
          "name": "getBalance",
          "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "owner",
          "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "tip",
          "outputs": [],
          "stateMutability": "payable",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "withdrawTips",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        }
      ]
    }
  }
} as const
