// ⚠️  Auto-generated by 'npm run deploy' — do not edit manually
//    'npm run deploy'         → localhost 배포
//    'npm run deploy:sepolia' → Sepolia 배포
export const deployedContracts = {} as const
