import { HardhatRuntimeEnvironment } from 'hardhat/types'
import { DeployFunction } from 'hardhat-deploy/types'
import * as fs from 'fs'
import * as path from 'path'

const OUTPUT_PATH = path.join(__dirname, '../../nextjs/contracts/deployedContracts.ts')

const deploy: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const { deployments, getNamedAccounts, network } = hre
  const { deploy } = deployments
  const { deployer } = await getNamedAccounts()

  console.log(`\n📦 Deploying TipJar`)
  console.log(`   Network  : ${network.name}`)
  console.log(`   Deployer : ${deployer}\n`)

  const result = await deploy('TipJar', {
    from: deployer,
    args: [],
    log: true,
    autoMine: true, // 로컬 네트워크에서 즉시 채굴
  })

  console.log(`\n✅ TipJar → ${result.address}`)

  // ── SE-2 핵심: deployedContracts.ts 자동 생성 ──────────────────
  await generateDeployedContracts(hre, result.address)
}

async function generateDeployedContracts(hre: HardhatRuntimeEnvironment, address: string) {
  const artifact = await hre.artifacts.readArtifact('TipJar')

  // 기존 파일이 있으면 다른 네트워크 배포 정보와 병합
  let existing: Record<string, unknown> = {}
  if (fs.existsSync(OUTPUT_PATH)) {
    const raw = fs.readFileSync(OUTPUT_PATH, 'utf-8')
    const match = raw.match(/= ({[\s\S]*}) as const/)
    if (match) {
      try { existing = JSON.parse(match[1]) } catch {}
    }
  }

  const updated = {
    ...existing,
    [hre.network.name]: {
      TipJar: {
        address,
        abi: artifact.abi,
      },
    },
  }

  const banner = `\
// ⚠️  Auto-generated by 'npm run deploy' — do not edit manually
//    'npm run deploy'         → localhost 배포
//    'npm run deploy:sepolia' → Sepolia 배포
`
  fs.writeFileSync(
    OUTPUT_PATH,
    `${banner}export const deployedContracts = ${JSON.stringify(updated, null, 2)} as const\n`
  )

  console.log(`\n📝 packages/nextjs/contracts/deployedContracts.ts 업데이트 완료`)
}

deploy.tags = ['TipJar']
export default deploy
